//! `action-reference` — emit (and drift-check) the generated action
//! authoring reference at `docs/action-reference.md`.
//!
//!     cargo run -p xtask -- action-reference           # write the doc
//!     cargo run -p xtask -- action-reference --check   # fail if stale
//!
//! The reference is the version-exact **retrieval payload** for authoring
//! a Verification Definition without Duhem pretraining (spec #248): every
//! built-in action's `with:` fields, closed enums, outputs, and a worked
//! example — generated from `duhem_actions::catalog()` so it can't drift
//! from the code that `duhem validate` / `duhem run` enforce. `--check` is
//! the CI guard against staleness, mirroring `schema-json`.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use duhem_actions::catalog;

const DOC_PATH: &str = "docs/action-reference.md";

pub fn run(args: Vec<String>) -> Result<()> {
    let check = args.iter().any(|a| a == "--check");
    let out_path = workspace_root()?.join(DOC_PATH);
    let generated = render();

    if check {
        let on_disk = std::fs::read_to_string(&out_path).with_context(|| {
            format!(
                "read {} (run `cargo run -p xtask -- action-reference` to generate it)",
                out_path.display()
            )
        })?;
        if on_disk != generated {
            bail!(
                "{DOC_PATH} is out of date with the action contracts.\n\
                 Run `cargo run -p xtask -- action-reference` to regenerate it."
            );
        }
        eprintln!("action-reference: {DOC_PATH} is up to date");
        return Ok(());
    }

    std::fs::write(&out_path, &generated)
        .with_context(|| format!("write {}", out_path.display()))?;
    eprintln!("action-reference: wrote {DOC_PATH}");
    Ok(())
}

/// Render the reference as Markdown. Deterministic: `catalog()` order is
/// fixed and we group by a fixed family order.
fn render() -> String {
    let mut s = String::new();
    s.push_str(
        "<!-- GENERATED by `cargo run -p xtask -- action-reference` from the action\n     contracts (duhem_actions::catalog()). Do not edit by hand; run the command\n     to regenerate. Drift-checked in CI. -->\n\n",
    );
    s.push_str("# Action reference\n\n");
    s.push_str(
        "Version-exact ground truth for authoring a Verification Definition — every\nbuilt-in action's `with:` fields, `outputs`, and a worked example. Generated from\nthe action contracts, so it always matches what `duhem validate` / `duhem run`\naccept. `duhem describe <uses>` prints the same for one action; `duhem actions`\nlists the catalog.\n\n",
    );
    s.push_str(
        "Bind an output with `outputs: { <name>: <field> }`, then read it in an\nassertion as `$steps.<id>.outputs.<name>`. Assert over **scalar** outputs\n(`status`, `body_text`, `satisfied`, `exit_code`, …); helpers like\n`$runtime.contains(...)` cover membership.\n\n",
    );

    let cat = catalog();
    for family in ["ui", "api", "db", "cli"] {
        let prefix = format!("{family}/");
        let acts: Vec<_> = cat.iter().filter(|c| c.uses.starts_with(&prefix)).collect();
        if acts.is_empty() {
            continue;
        }
        s.push_str(&format!("## `{family}/*`\n\n"));
        for c in acts {
            s.push_str(&format!("### `{}`\n\n{}\n\n", c.uses, c.summary));
            s.push_str("| `with:` field | required | values |\n|---|:---:|---|\n");
            for f in &c.with {
                let req = if f.required { "yes" } else { "no" };
                let vals = if f.enum_values.is_empty() {
                    "—".to_string()
                } else {
                    format!("`{}`", f.enum_values.join("` \\| `"))
                };
                s.push_str(&format!("| `{}` | {req} | {vals} |\n", f.name));
            }
            s.push('\n');
            if c.outputs.is_empty() {
                s.push_str("**outputs:** (none)\n\n");
            } else {
                let outs: Vec<String> = c.outputs.iter().map(|o| format!("`{o}`")).collect();
                s.push_str(&format!("**outputs:** {}\n\n", outs.join(", ")));
            }
            s.push_str("```yaml\n");
            s.push_str(c.example);
            s.push_str("\n```\n\n");
        }
    }
    s
}

/// Workspace root = the parent of `xtask/` (this crate's manifest dir).
fn workspace_root() -> Result<PathBuf> {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .map(Path::to_path_buf)
        .context("could not resolve the workspace root from xtask/")
}
